[package]
name = "pong-tui"
version = "0.1.0"
description = "pong game tui in rust"
authors = ["patrickhaahr <117731913+patrickhaahr@users.noreply.github.com>"]
license = "MIT"
edition = "2024"

[dependencies]
crossterm = "0.28.1"
ratatui = "0.29.0"
color-eyre = "0.6.3"
